=== hmrc/individual-calculations-api/resources/public/api/conf/3.0/schemas/retrieve/retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Retrieve a Self Assessment Tax Calculation",
  "type": "object",
  "properties": {
    "metadata": {
      "$ref": "retrieve/metadata.json"
    },
    "inputs": {
      "$ref": "retrieve/inputs.json"
    },
    "calculation": {
      "$ref": "retrieve/calculation.json"
    },
    "messages": {
      "$ref": "retrieve/messages.json"
    }
  },
  "required": [
    "metadata",
    "inputs"
  ],
  "additionalProperties": "false"
}

=== hmrc/individual-calculations-api/test/resources/v7/retrieveCalculation/def1/model/response/calculation_mtd.json
{
  "metadata": {
    "calculationId": "f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c",
    "taxYear": "2017-18",
    "requestedBy": "customer",
    "requestedTimestamp": "2019-02-15T09:35:15.000Z",
    "calculationReason": "customer-request",
    "calculationTimestamp": "2019-02-15T09:35:15.094Z",
    "calculationType": "final-declaration",
    "intentToSubmitFinalDeclaration": true,
    "finalDeclaration": true,
    "finalDeclarationTimestamp": "2019-02-15T09:35:15.094Z",
    "periodFrom": "2018-04-06",
    "periodTo": "2019-04-05"
  },
  "inputs": {
    "personalInformation": {
      "identifier": "VO123456A",
      "dateOfBirth": "2018-04-06",
      "taxRegime": "uk",
      "statePensionAgeDate": "2050-04-06",
      "studentLoanPlan": [
        {
          "planType": "plan1"
        }
      ],
      "class2VoluntaryContributions": true,
      "marriageAllowance": "transferor",
      "uniqueTaxpayerReference": "1234567890"
    },
    "incomeSources": {
      "businessIncomeSources": [
        {
          "incomeSourceId": "000000000000210",
          "incomeSourceType": "self-employment",
          "incomeSourceName": "string",
          "accountingPeriodStartDate": "2018-04-06",
          "accountingPeriodEndDate": "2019-04-05",
          "source": "MTD-SA",
          "latestPeriodEndDate": "2021-12-02",
          "latestReceivedDateTime": "2021-12-02T15:25:48Z",
          "submissionPeriods": [
            {
              "periodId": "001",
              "startDate": "2018-04-06",
              "endDate": "2019-04-05",
              "receivedDateTime": "2019-02-15T09:35:04.843Z"
            }
          ]
        }
      ],
      "nonBusinessIncomeSources": [
        {
          "incomeSourceId": "000000000000210",
          "incomeSourceType": "uk-savings-and-gains",
          "incomeSourceName": "Savings Account 1",
          "startDate": "2018-04-06",
          "endDate": "2019-04-05",
          "source": "MTD-SA",
          "periodId": "001",
          "latestReceivedDateTime": "2019-08-01T13:02:09.775Z"
        }
      ]
    },
    "annualAdjustments": [
      {
        "incomeSourceId": "000000000000210",
        "incomeSourceType": "self-employment",
        "bsasId": "123a456b-789c-1d23-845e-678b9d1bd2ab",
        "receivedDateTime": "2021-12-02T15:25:48Z",
        "applied": true
      }
    ],
    "lossesBroughtForward": [
      {
        "lossId": "0yriP9QrW2jTa6n",
        "incomeSourceId": "000000000000210",
        "incomeSourceType": "self-employment",
        "submissionTimestamp": "2021-12-02T15:25:48Z",
        "lossType": "income",
        "taxYearLossIncurred": "2017-18",
        "currentLossValue": 12500,
        "mtdLoss": false
      }
    ],
    "claims": [
      {
        "claimId": "0vayS9JrW2jTa6n",
        "originatingClaimId": "0vayS9JrW2jTa6n",
        "incomeSourceId": "000000000000210",
        "incomeSourceType": "self-employment",
        "submissionTimestamp": "2021-12-02T15:25:48Z",
        "taxYearClaimMade": "2017-18",
        "claimType": "carry-forward",
        "sequence": 0
      }
    ],
    "constructionIndustryScheme": [
      {
        "employerRef": "123/AA12345",
        "contractorName": "string",
        "periodData": [
          {
            "deductionFromDate": "2021-12-02",
            "deductionToDate": "2021-12-02",
            "submissionTimestamp": "2021-12-02T15:25:48Z",
            "source": "contractor",
            "deductionAmount": 5000.99
          }
        ]
      }
    ],
    "allowancesReliefsAndDeductions": [
      {
        "type": "investment-reliefs",
        "submittedTimestamp": "2021-12-02T15:25:48Z",
        "startDate": "2021-12-02",
        "endDate": "2021-12-02",
        "source": "MTD-SA"
      }
    ],
    "pensionContributionAndCharges": [
      {
        "type": "pension-reliefs",
        "submissionTimestamp": "2021-12-02T15:25:48Z",
        "startDate": "2021-12-02",
        "endDate": "2021-12-02",
        "source": "customer"
      }
    ],
    "other": [
      {
        "type": "coding-out",
        "submittedOn": "2021-12-02T15:25:48Z"
      }
    ]
  },
  "calculation": {
    "allowancesAndDeductions": {
      "personalAllowance": 12500,
      "marriageAllowanceTransferOut": {
        "personalAllowanceBeforeTransferOut": 5000.99,
        "transferredOutAmount": 5000.99
      },
      "reducedPersonalAllowance": 12501,
      "giftOfInvestmentsAndPropertyToCharity": 12502,
      "blindPersonsAllowance": 12503,
      "lossesAppliedToGeneralIncome": 12504,
      "cgtLossSetAgainstInYearGeneralIncome": 12505,
      "qualifyingLoanInterestFromInvestments": 5001.99,
      "postCessationTradeReceipts": 5002.99,
      "paymentsToTradeUnionsForDeathBenefits": 5003.99,
      "grossAnnuityPayments": 5004.99,
      "annuityPayments": {
        "reliefClaimed": 5000.99,
        "rate": 20.01
      },
      "pensionContributions": 5000.99,
      "pensionContributionsDetail": {
        "retirementAnnuityPayments": 5000.99,
        "paymentToEmployersSchemeNoTaxRelief": 5000.99,
        "overseasPensionSchemeContributions": 5000.99
      }
    },
    "reliefs": {
      "residentialFinanceCosts": {
        "adjustedTotalIncome": 5000.99,
        "totalAllowableAmount": 5000.99,
        "relievableAmount": 5000.99,
        "rate": 20.01,
        "totalResidentialFinanceCostsRelief": 5000.99,
        "ukProperty": {
          "amountClaimed": 12500,
          "allowableAmount": 5000.99,
          "carryForwardAmount": 5000.99
        },
        "foreignProperty": {
          "totalForeignPropertyAllowableAmount": 5000.99,
          "foreignPropertyRfcDetail": [
            {
              "countryCode": "FRA",
              "amountClaimed": 12500,
              "allowableAmount": 5000.99,
              "carryForwardAmount": 5000.99
            }
          ]
        },
        "allOtherIncomeReceivedWhilstAbroad": {
          "totalOtherIncomeAllowableAmount": 5000.99,
          "otherIncomeRfcDetail": [
            {
              "countryCode": "FRA",
              "residentialFinancialCostAmount": 5000.99,
              "broughtFwdResidentialFinancialCostAmount": 5000.99
            }
          ]
        }
      },
      "reliefsClaimed": [
        {
          "type": "vct-subscriptions",
          "amountClaimed": 5000.99,
          "allowableAmount": 5000.99,
          "amountUsed": 5000.99,
          "rate": 20.01,
          "reliefsClaimedDetail": [
            {
              "amountClaimed": 5000.99,
              "uniqueInvestmentRef": "string",
              "name": "string",
              "socialEnterpriseName": "string",
              "companyName": "string",
              "deficiencyReliefType": "life-insurance",
              "customerReference": "string"
            }
          ]
        }
      ],
      "foreignTaxCreditRelief": {
        "customerCalculatedRelief": true,
        "totalForeignTaxCreditRelief": 5000.99,
        "foreignTaxCreditReliefOnProperty": 5000.99,
        "foreignTaxCreditReliefOnDividends": 5000.99,
        "foreignTaxCreditReliefOnSavings": 5000.99,
        "foreignTaxCreditReliefOnForeignIncome": 5000.99,
        "foreignTaxCreditReliefDetail": [
          {
            "incomeSourceType": "foreign-property",
            "incomeSourceId": "000000000000210",
            "countryCode": "FRA",
            "foreignIncome": 5001.99,
            "foreignTax": 5002.99,
            "dtaRate": 20,
            "dtaAmount": 5003.99,
            "ukLiabilityOnIncome": 5004.99,
            "foreignTaxCredit": 5005.99,
            "employmentLumpSum": true
          }
        ]
      },
      "topSlicingRelief": {
        "amount": 5000.99
      }
    },
    "taxDeductedAtSource": {
      "bbsi": 5000.99,
      "ukLandAndProperty": 5000.99,
      "cis": 5000.99,
      "securities": 5000.99,
      "voidedIsa": 5000.99,
      "payeEmployments": 5000.99,
      "occupationalPensions": 5000.99,
      "stateBenefits": -99999999999.99,
      "specialWithholdingTaxOrUkTaxPaid": 5000.99,
      "inYearAdjustmentCodedInLaterTaxYear": 5000.99
    },
    "giftAid": {
      "grossGiftAidPayments": 12500,
      "rate": 20.01,
      "giftAidTax": 5000.99,
      "giftAidTaxReductions": 5000.99,
      "incomeTaxChargedAfterGiftAidTaxReductions": 5000.99,
      "giftAidCharge": 5000.99
    },
    "royaltyPayments": {
      "royaltyPaymentsAmount": 12500,
      "rate": 20.01,
      "grossRoyaltyPayments": 12500
    },
    "notionalTax": {
      "chargeableGains": 5000.99
    },
    "marriageAllowanceTransferredIn": {
      "amount": 5000.99,
      "rate": 20.01
    },
    "pensionContributionReliefs": {
      "totalPensionContributionReliefs": 5000.99,
      "pensionContributionDetail": {
        "regularPensionContributions": 5000.99,
        "oneOffPensionContributionsPaid": 5000.99
      }
    },
    "pensionSavingsTaxCharges": {
      "totalPensionCharges": 5000.99,
      "totalTaxPaid": 5000.99,
      "totalPensionChargesDue": 5000.99,
      "pensionSavingsTaxChargesDetail": {
        "excessOfLifeTimeAllowance": {
          "totalChargeableAmount": 5000.99,
          "totalTaxPaid": 5000.99,
          "lumpSumBenefitTakenInExcessOfLifetimeAllowance": {
            "amount": 5000.99,
            "taxPaid": 5000.99,
            "rate": 20.01,
            "chargeableAmount": 5000.99
          },
          "benefitInExcessOfLifetimeAllowance": {
            "amount": 5000.99,
            "taxPaid": 5000.99,
            "rate": 20.01,
            "chargeableAmount": 5000.99
          }
        },
        "pensionSchemeUnauthorisedPayments": {
          "totalChargeableAmount": 5000.99,
          "totalTaxPaid": 5000.99,
          "pensionSchemeUnauthorisedPaymentsSurcharge": {
            "amount": 5000.99,
            "taxPaid": 5000.99,
            "rate": 20.01,
            "chargeableAmount": 5000.99
          },
          "pensionSchemeUnauthorisedPaymentsNonSurcharge": {
            "amount": 5000.99,
