=== hmrc/individual-calculations-api/resources/public/api/conf/2.0/schemas/selfAssessment/retrieveTaxCalc/retrieve_metadata_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Self Assessment Tax Calculation Metadata",
  "description": "Retrieve Self Assessment Tax Calculation Metadata",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier of the calculation.",
      "type": "string",
      "pattern": "^[0-9]{8}|[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
      "example": "f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c"
    },
    "taxYear": {
      "description": "The tax year in which the calculation was performed in the format YYYY-YY",
      "type": "string",
      "example": "2019-20"
    },
    "requestedBy": {
      "description": "The requestor of the calculation. Currently agent will default to customer until it can be supported.",
      "type": "string",
      "enum": [
        "customer",
        "hmrc",
        "agent"
      ]
    },
    "calculationReason": {
      "description": "The reason why the calculation was triggered",
      "type": "string",
      "oneOf": [
        {
          "enum": [
            "customerRequest"
          ],
          "description": "The calculation was triggered by the customer via software."
        },
        {
          "enum": [
            "class2NICEvent"
          ],
          "description": "The calculation was triggered internally by HMRC once the actual Class 2 NIC amount is available. This event is only applicable for an in-year \"crystallisation\" calculation type."
        },
        {
          "enum": [
            "newLossEvent"
          ],
          "description": "The calculation was triggered internally by HMRC on receipt of a new pre-MTD brought forward loss made by the customer. This event is only applicable for a \"crystallisation\" calculation type. This event is not currently supported and will be supported in the future."
        },
        {
          "enum": [
            "newClaimEvent"
          ],
          "description": "The calculation was triggered internally by HMRC on receipt of a new loss claim made by the customer. This event is only applicable for a \"crystallisation\" calculation type. This event is not currently supported and will be supported in the future."
        },
        {
          "enum": [
            "updatedClaimEvent"
          ],
          "description": "The calculation was triggered internally by HMRC on receipt of an updated loss claim made by the customer. This event is only applicable for a \"crystallisation\" calculation type. This event is not currently supported and will be supported in the future."
        },
        {
          "enum": [
            "updatedLossEvent"
          ],
          "description": "The calculation was triggered internally by HMRC on receipt of an updated pre-MTD brought forward loss made by the customer. This event is only applicable for a \"crystallisation\" calculation type. This event is not currently supported and will be supported in the future."
        },
        {
          "enum": [
            "newAnnualAdjustmentEvent"
          ],
          "description": "The calculation was triggered internally by HMRC on receipt of a request for a new adjustable summary calculation by the customer. This event is not currently supported."
        },
        {
          "enum": [
            "updatedAnnualAdjustmentEvent"
          ],
          "description": "The calculation was triggered internally by HMRC on receipt of an adjustment to an adjustable summary calculation made by the customer. This event is not currently supported."
        },
        {
          "enum": [
            "unattendedCalculation"
          ],
          "description": "The calculation was triggered without attendence <filler content>. This event is not currently supported."
        }
      ]
    },
    "calculationTimestamp": {
      "description": "The timestamp of when the calculation was performed in ISO8601 UTC format: YYYY-MM-DDThh:mm:ssZ.",
      "type": "string",
      "example": "2019-06-17T09:22:59Z"
    },
    "calculationType": {
      "description": "The type of calculation performed. A \"crystallisation\" calculation is a calculation triggered via the \"Intent to crystallise\" endpoint under the \"Self Assessment (MTD)\" API.",
      "type": "string",
      "enum": [
        "inYear",
        "crystallisation"
      ]
    },
    "intentToCrystallise": {
      "description": "Boolean value showing whether the calculation is intended to be crystallised against. Valid values are true or false",
      "type": "boolean",
      "example": "true"
    },
    "crystallised": {
      "description": "Boolean value showing whether the calculation is intended to be crystallised against. Valid values are true or false",
      "type": "boolean",
      "example": "true"
    },
    "totalIncomeTaxAndNicsDue": {
      "description": "The total amount of Income Tax and National Insurance Contributions due. This field is not present if the calculationErrorCount value is greater than zero. This value must be between -99999999999.99 and 99999999999.99.",
      "type": "number",
      "multipleOf": 0.01,
      "minimum": -99999999999.99,
      "maximum": 99999999999.99,
      "example": "2000.98"
    },
    "calculationErrorCount": {
      "description": "A count of error messages generated during the calculation. If the field is present it indicates a calculation has not been performed. Further detail can be found in the \"Retrieve Self Assessment tax calculation messages\" endpoint about the errors.",
      "type": "number",
      "multipleOf": 1,
      "minimum": 1,
      "example": "2"
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A list of endpoint links that indicate possible actions related to the current resource",
        "properties": {
          "href": {
            "description": "The relative url of the endpoint",
            "type": "string",
            "example": "/individuals/calculations/{nino}/self-assessment/{calculationId}"
          },
          "rel": {
            "description": "A label for the endpoint, which describes how it is related to the current resource\nThe rel will be self where the action is retrieval of the same resource",
            "type": "string",
            "enum": [
              "self",
              "income-tax-and-nics-calculated",
              "taxable-income",
              "allowances-deductions-reliefs",
              "end-of-year-estimate",
              "messages"

            ]
          },
          "method": {
            "description": "The HTTP method type for the endpoint",
            "type": "string",
            "enum": [
              "GET"
            ]
          }
        },
        "required": [
          "href",
          "rel",
          "method"
        ]
      }
    }
  },
  "required": [
    "id",
    "taxYear",
    "requestedBy",
    "calculationReason",
    "calculationType",
    "intentToCrystallise",
    "crystallised"
  ]
}

=== hmrc/individual-calculations-api/resources/public/api/conf/1.0/examples/selfAssessment/retrieveMetadata/retrieve_calc_inYear_response.json
{
  "id": "b03921dc-8e23-5e8a-bf0e-55a8e3904673",
  "taxYear": "2018-19",
  "requestedBy": "customer",
  "calculationReason": "customerRequest",
  "calculationTimestamp": "2019-02-15T08:22:15.094Z",
  "calculationType": "inYear",
  "intentToCrystallise": false,
  "crystallised": false,
  "totalIncomeTaxAndNicsDue": 2000.98,
  "links": [
    {
      "href": "/individuals/calculations/RW399019B/self-assessment/f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/calculations/RW399019B/self-assessment/f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c/income-tax-nics-calculated",
      "rel": "income-tax-and-nics-calculated",
      "method": "GET"
    },
    {
      "href": "/individuals/calculations/RW399019B/self-assessment/f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c/taxable-income",
      "rel": "taxable-income",
      "method": "GET"
    },
    {
      "href": "/individuals/calculations/RW399019B/self-assessment/f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c/allowances-deductions-reliefs",
      "rel": "allowances-deductions-reliefs",
      "method": "GET"
    },
    {
      "href": "/individuals/calculations/RW399019B/self-assessment/f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c/end-of-year-estimate",
      "rel": "end-of-year-estimate",
      "method": "GET"
    },
    {
      "href": "/individuals/calculations/RW399019B/self-assessment/f2fb30e5-4ab6-4a29-b3c1-c7264259ff1c/messages",
      "rel": "messages",
      "method": "GET"
    }
  ]
}
